spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/beautystor_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:false}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=PT15M
jwt.refresh-token-expiration=P7D
